"""initial_postgres

Revision ID: 3a10ebb3cb97
Revises: 
Create Date: 2026-06-03 12:12:02.321243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a10ebb3cb97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('user_email', sa.String(length=320), nullable=False),
    sa.Column('schedule_interval', sa.String(length=20), nullable=False),
    sa.Column('selected_sites', sa.Text(), nullable=False),
    sa.Column('alert_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_lowest_price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('sites_checked', sa.Text(), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=False),
    sa.Column('lowest_price', sa.Float(), nullable=True),
    sa.Column('lowest_site', sa.String(length=200), nullable=True),
    sa.Column('alert_triggered', sa.Boolean(), nullable=True),
    sa.Column('error_sites', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['watchlist_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('run_result_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_to', sa.String(length=320), nullable=False),
    sa.Column('sites_below_target', sa.Text(), nullable=False),
    sa.Column('lowest_price_found', sa.Float(), nullable=False),
    sa.Column('send_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['watchlist_jobs.id'], ),
    sa.ForeignKeyConstraint(['run_result_id'], ['run_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_log')
    op.drop_table('run_results')
    op.drop_table('watchlist_jobs')
    # ### end Alembic commands ###
