# """add_job_type

# Revision ID: db70e42e2f08
# Revises: 
# Create Date: 2026-06-02 18:06:07.598865

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = 'db70e42e2f08'
# down_revision: Union[str, None] = None
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     # op.add_column('watchlist_jobs', sa.Column('job_type', sa.String(length=20), nullable=False))
#     op.add_column('watchlist_jobs', sa.Column('job_type', sa.String(length=20), nullable=False, server_default='price_watch'))
#     op.alter_column('watchlist_jobs', 'target_price',
#                existing_type=sa.FLOAT(),
#                nullable=True)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('watchlist_jobs', 'target_price',
#                existing_type=sa.FLOAT(),
#                nullable=False)
#     op.drop_column('watchlist_jobs', 'job_type')
#     # ### end Alembic commands ###


"""add_job_type

Revision ID: db70e42e2f08
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'db70e42e2f08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite doesn't support ALTER COLUMN, so we rebuild the table.
    with op.batch_alter_table('watchlist_jobs', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('job_type', sa.String(length=20), nullable=False, server_default='price_watch'))
        batch_op.alter_column('target_price', existing_type=sa.Float(), nullable=True)


def downgrade() -> None:
    with op.batch_alter_table('watchlist_jobs', recreate='always') as batch_op:
        batch_op.drop_column('job_type')
        batch_op.alter_column('target_price', existing_type=sa.Float(), nullable=False)